site_name: HowDoI

theme:
    name: 'material'
    palette:
        primary: ''
        accent: 'teal'
    icon:
        repo: fontawesome/brands/github

repo_name: gleitz/howdoi
repo_url: https://github.com/gleitz/howdoi
edit_uri: ''

nav:
    - HowDoI: index.md
    - Installation: installation.md
    - "User Guide": user-guide.md
    - Contributing: contributing.md

markdown_extensions:
    - admonition
    - codehilite:
          pygments_style: monokai
    - markdown_include.include:
          base_path: docs
    - pymdownx.tabbed

extra:
    social:
      - icon: fontawesome/brands/github
        link: 'https://github.com/gleitz/howdoi'